#!/bin/bash
# coding BY: MOHAMED_OS

Link='https://gitlab.com/hanfy1971/ipaudiopro/-/raw/main/'
pyv=$(python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))")
PkgName="enigma2-plugin-extensions-ipaudiopro"

if [ -f /etc/opkg/opkg.conf ]; then
    status='/var/lib/opkg/status'
    update='opkg update'
    install='opkg install'
    remove='opkg remove --force-depends'
elif [ -f /etc/apt/apt.conf ]; then
    printf '(!) sorry image not supported!'
    sleep 2
    exit 0
fi

case $(uname -m) in
armv7l*) platform="cortexa15hf-neon-vfpv4" ;;
mips*) platform="mips32el" ;;
aarch64*) platform="aarch64" ;;
esac

${update} >/dev/null 2>&1

e2_depndes() {
    if ! grep -qs "Package: $1" "${status}"; then
        wait
        printf "========| Need to install %s |========" "$1"
        ${install} "$1"
        wait
        clear
    fi
}

cam_del_old_versions() {
    if grep -qs "Package: $1" "${status}"; then
        ${remove} "$1"
    fi
}

arrVar=("alsa-conf" "alsa-plugins" "alsa-state" "enigma2" "libasound2" "libc6" "libgcc1" "libgcc1" "libstdc++6" "libpython${pyv}-1.0")
if [ "$(python -c"from sys import version_info; print(version_info[0])")" = 3 ]; then
    arrVar+=("python3-cryptography" "libavcodec60" "libavformat60")
else
    arrVar+=("python-cryptography" "libavcodec58" "libavformat58")
fi

for i in "${arrVar[@]}"; do
    e2_depndes "$i"
done

curl --help >/dev/null 2>&1 && DOWNLOADER="curl -L -J -s -o" || DOWNLOADER="wget --no-check-certificate -q -O"

VER=$($DOWNLOADER - "${Link}version")

[ -z "$VER" ] && {
    printf "Error ! The online version was not recognized !\n"
    exit 1
}

FNAME=${PkgName}_${VER}_${platform}.ipk

rm -f "/tmp/${FNAME}"

$DOWNLOADER "/tmp/${FNAME}" "${Link}PY${pyv}/${FNAME}" || {
    printf "Error ! File download failed !\n"
    exit 1
}

cam_del_old_versions ${PkgName}

${install} "/tmp/${FNAME}"

rm -f "/tmp/${FNAME}"
